# Configuration file for MegaLinter

DISABLE_LINTERS:
  - PYTHON_BANDIT
  - PYTHON_MYPY
  - PYTHON_PYRIGHT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE

REPORT_OUTPUT_FOLDER: none
CLEAR_REPORT_FOLDER: true
IGNORE_GITIGNORED_FILES: true
REPOSITORY_GRYPE_ARGUMENTS: --only-fixed
