---
# Configuration file for MegaLinter

DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - JSON_V8R
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_MYPY
  - PYTHON_PYLINT
  - PYTHON_PYRIGHT
  - REPOSITORY_CHECKOV
  - REPOSITORY_GITLEAKS
  - REPOSITORY_KICS
  - REPOSITORY_TRIVY
  - SPELL_LYCHEE
  - YAML_V8R
  - YAML_YAMLLINT

REPORT_OUTPUT_FOLDER: none
CLEAR_REPORT_FOLDER: true
IGNORE_GITIGNORED_FILES: true
REPOSITORY_GRYPE_ARGUMENTS: --only-fixed
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: (.cspell.json|renovate.json)
