---
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-wf-example
  namespace: argo
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    serviceAccountName: argo-workflow
    entrypoint: main
    templates:
      - name: main
        container:
          image: alpine:3.18
          command:
            - sh
            - -c
            - |
              echo "I am a CronWorkflow"
              echo "It is currently $(date)"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "10m"
