apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: versions-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  templates:
    - name: main
      dag:
        tasks:
          - name: kubernetes-version
            template: kubernetes-version
          - name: kubectl-versions
            template: kubectl-versions
            arguments:
              parameters:
                - name: label
                  value: "{{item.label}}"
                - name: hrname
                  value: "{{item.hrname}}"
            withItems:
              - { label: "app.kubernetes.io/component=workflow-controller", hrname: "Argo Workflows" }
              - { label: "app.kubernetes.io/name=pipekit-agent", hrname: "Pipekit Agent" }
              - { label: "app=minio", hrname: "Minio" }

    - name: kubernetes-version
      container:
        image: dtzar/helm-kubectl
        command:
          - /bin/bash
          - -c
          - |
            kubectl version

    - name: kubectl-versions
      inputs:
        parameters:
          - name: label
          - name: hrname
      container:
        image: dtzar/helm-kubectl
        command:
          - /bin/bash
          - -c
          - |
            version=$(kubectl -n pipekit get deployment -l {{inputs.parameters.label}} -o=jsonpath="{..image}")
            echo "{{inputs.parameters.hrname}}: $version"
