---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: versions-
  namespace: argo
spec:
  entrypoint: main
  serviceAccountName: argo-workflow
  templates:
    - name: main
      dag:
        tasks:
          - name: kubernetes-version
            template: kubernetes-version
          - name: kubectl-versions
            template: kubectl-versions
            arguments:
              parameters:
                - name: label
                  value: "{{item.label}}"
                - name: hrname
                  value: "{{item.hrname}}"
                - name: type
                  value: "{{item.type}}"
            withItems:
              - {
                  label: "app.kubernetes.io/component=workflow-controller",
                  hrname: "Argo Workflows",
                  type: "deployment",
                }
              - {
                  label: "app.kubernetes.io/name=pipekit-agent",
                  hrname: "Pipekit Agent",
                  type: "deployment",
                }
              - { label: "app=minio", hrname: "Minio", type: "statefulset" }

    - name: kubernetes-version
      container:
        image: dtzar/helm-kubectl:3.17.2
        command:
          - /bin/bash
          - -c
          - |
            kubectl version
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"

    - name: kubectl-versions
      inputs:
        parameters:
          - name: label
          - name: hrname
          - name: type
      container:
        image: dtzar/helm-kubectl:3.17.2
        command:
          - /bin/bash
          - -c
          - |
            version=$(kubectl -n pipekit get {{inputs.parameters.type}} -l {{inputs.parameters.label}} -o=jsonpath="{..image}")
            echo "{{inputs.parameters.hrname}}: $version"
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
