apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: job-logs-
  namespace: argo
spec:
  entrypoint: hellopipekit
  serviceAccountName: argo-workflow
  templates:
    - name: hellopipekit
      resource:
        action: create
        setOwnerReference: true
        successCondition: status.succeeded > 0
        failureCondition: status.failed > 3
        manifest: |
          apiVersion: batch/v1
          kind: Job
          metadata:
            generateName: hellopipekit-job-
          spec:
            template:
              metadata:
                name: hellopipekit
                labels:
                  workflows.argoproj.io/workflow: {{workflow.name}}
              spec:
                containers:
                - name: hellopipekit
                  image: alpine:3.19
                  command: ["sh", "-c"]
                  args: [ "echo \"Hello Pipekit!\"" ]
                restartPolicy: Never
            backoffLimit: 4
